### ISSUE TITLE
Minutes for Client Meeting @ZiPing

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#30]
### **Meeting Minutes:**

**Item 1: Initial requirement 6 on displaying under allocated and over allocated staff.** 

Client highlighted that our prototype for over allocated staff needs to be changed to over allocated over 40 hours of work.

**Item 2: Initial requirement 10 on Staff can reject jobs but will be warned by manager.** 

Client explained that job allocation is done week by week starting from wednesday and ending on thursday on the same week, Staff has until wednesday 2359 to reject allocated jobs, Staff is also expected to approach the manager and give reasons (not the other way around). 

Manager will do the reallocation of jobs on thursday and approve successful rejections. After thursday 2359, system will auto approve all requests.

On friday, staff can see the allocation.

**Item 3: On user login and timeout**

Client highlighted that 2FA should be a baseline for all accounts. Client highlighted that 2FA can use Microsoft Authenticator.
Client wants a feature for session monitoring and auto-logout after 10mins of inactivity.
Login Credentials should use work email as their username.

**Item 4: On staff availability**

Client said that Staff should not be able to see other staff's timetable. Manager can see all staff's timetable.
Client also said that manager should be able to edit, delete job allocations.
Client said that the managers do not need to see other manager's timetable.

**Item 5: Concerns for future scaling of the application**

Client wants the maximum number of users configurable in terms of features and job appointments.

**Item 6: Website response time**

Client wants it to be regular speed, no lags.

**Item 7: Website Accessibility, Language and Color**

Client said they don't need because the job appointments can't be done by challenged people.
Client said that English is enough.
Client said that they have no particular color scheme.

**Item 8: Train timings and staff scheduling**
Based on the project description, the train runs in one way for 4 hours per route from Singapore to Kuala Lumpur. 

Client clarified that the schedule should be on a per day basis, 1 group of people going from SG to KL and then back to a total of 8hrs.

**Item 8: Check job preference for staff**

Client said that the features should be on the landing page for user friendliness. Client is ok with having a calendar and pick what time the staff is available/unavailable.

**Comment by Excelic** [comment]
Changes to be made after client meeting:

label correctly wireframe screen due to mistake with wording
add login authentication with 2FA
add session log out after 10min
remove other staff shift for staff page
manager can edit job
add in appointments based on staff role
add in shift as a full working day(8hr)
landing job should have all feature to make friendly

**Comment by ShadeRemix** [comment]
Okay! Updated and completed
