### ISSUE TITLE
Mockup for rejection approval and rejection disapproval page on shared PPT

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#33]

**Comment by edwin3746** [comment]
Prototype Task Updates:

- [ ] Review Page (Manager perspective to replace Rejection Approval and Disapproval page)



![Image](https://user-images.githubusercontent.com/64019173/195299248-697f03e3-09f9-4044-83c9-60be8b4a2e67.png)



- [ ] Combined Create User Page with Landing Page (Admin)

![Image](https://user-images.githubusercontent.com/64019173/195299071-8a0b674f-336a-4883-b118-07563d68c6e0.png)


- [ ] Created Staff List Page (Admin)

![Image](https://user-images.githubusercontent.com/64019173/195298888-ea44b653-6027-467e-acdc-ddeb37300b52.png)
