### ISSUE TITLE
M1 Report - Gantt Chart for M1 (Jun Hao)

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#36]
To be done by 24 sep 2359

**Comment by ShadeRemix** [comment]
Gantt Chart has been added, need to review before closing

**Comment by edwin3746** [comment]
Completed Gantt Chart
- For Project Conception, Initiation and Analysis Phase
    - Filled in duration(days) for M1
- For Design, Implementation. Testing and Maintenance Phase
    - Forecasted dates to commence on tasks within each phase

Gantt Chart has been added to Project Repository

**Comment by ShadeRemix** [comment]
Need to add dates for M2 and M3

**Comment by ShadeRemix** [comment]
Gantt Chart completed, Gantt Chart xlsx and Jpg files uploaded to repos.
