### ISSUE TITLE
M1 Report - Edwin

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#39]
Report part 1.1, 1.2, 1.3, to be done by 24 sep 2359.

**Comment by edwin3746** [comment]
Tasks Updates
- Completed 1.1 Product scope
- Completed 1.2 Related Background Literature
    - Researched and presented two relevant studies on staff scheduling 
- Completed 1.3 Intended Audience and Document Overview
