### ISSUE TITLE
Meeting For M1 @  23 Sep 2022 1pm SIT@NYP@DR2G

### ISSUE THREAD

**Issue by edwin3746** [LawJunHao/ICT2201-Team-Project-T8#46]
Agenda of this meeting:
M1 Report
- Prototype
    - Me and Jun Hao will work on and finalise the protoype with the pointers received from the client meeting
- Requirements
    - We will go through the Functional and Non-Functional Requirements to ensure consistency
- Project Estimation and Plan 
    - Convert WBS to a form with in-depth task breakdown into subtasks

**Comment by edwin3746** [comment]
Feel free to add on any stuff I've missed out!

**Comment by ShadeRemix** [comment]
Meeting done, completed the following.

Prototype
-Me and Jun Hao will work on and finalise the protoype with the pointers received from the client meeting
Requirements
-We will go through the Functional and Non-Functional Requirements to ensure consistency
Project Estimation and Plan
-Convert WBS to a form with in-depth task breakdown into subtasks

And revised the use case requirements and Gantt Chart
