### ISSUE TITLE
M1 Mistakes to fix

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#51]
M1 report pointers to fix.

**Comment by Excelic** [comment]
- [ ] UML diagram - Changes have been made to ensure that future milestone will be using the new Diagram


![Image](https://user-images.githubusercontent.com/24997390/194509605-2cab26ee-1a0c-464b-898d-513e0ce05811.jpg)


- [ ] Labeling for tables - Table without label has been fixed, all table has been re-label as well


![Image](https://user-images.githubusercontent.com/24997390/194509981-63895018-1ee2-4a84-ac7b-a212350c4951.PNG)

 

- [ ] Not supposed to say starting implementation phase currently, and assign tasks to the right people. - currently removed. 
- [ ] 
- [ ] Size estimation - This has been updated, all images related to this have been moved from appendix to part of the size estimation section

**Comment by edwin3746** [comment]
- [ ] Background review - considered elicitation, find stuff related to train scheduling and past ideas or mistakes. Align with what customer wants and in same industry (trains).

![Image](https://user-images.githubusercontent.com/64019173/194700626-ca3321f1-2274-4a5d-98c7-48e983808d38.png)

- [ ] Specific Requirements - need to include our elicitation method. remove URI3 cause got nothing.
![Image](https://user-images.githubusercontent.com/64019173/194700627-32498dec-c6e7-45f0-90b7-4cf95425cd8a.png)

**Comment by Excelic** [comment]
Issue shall be closed as M1 mistakes are fixed, thus proceeding will be carried over to M2
