### ISSUE TITLE
What went well in Milestone 1?

### ISSUE THREAD

**Issue by edwin3746** [LawJunHao/ICT2201-Team-Project-T8#52]
Discuss and comment what you guys think went well for the first M1 section of the project.

**Comment by ShadeRemix** [comment]
Team communicated well

**Comment by Excelic** [comment]
Workload was spread equally to each memeber of the team, with each memeber being proficient at the task they were assigned to.

**Comment by edwin3746** [comment]
There was good team dynamics with everyone working towards a shared goal.

**Comment by LawJunHao** [comment]
The team did not rely heavily on the team leader for initiation of communication between the needed components. Therefore, things such as regular updates as well as consistent goals were present throughout the entire M1 phase.
