### ISSUE TITLE
What could be improved?

### ISSUE THREAD

**Issue by edwin3746** [LawJunHao/ICT2201-Team-Project-T8#53]
Assignees must ensure improvements are implemented in the subsequent milestones.

**Comment by Excelic** [comment]
Time management was an issue as we did not strictly follow through our projected schedule for the M1 milestone.

**Comment by edwin3746** [comment]
Slack communication can be improved, as most of our discussions happened in the meetings. We should have more discussions regarding the project progress in Slack, as it is an important tool used by businesses for communication.

**Comment by LawJunHao** [comment]
The things we delivered were not alinged with the things needed in general. There were some items that were not refined enough upon submission and needed either further proof reading or lacking of quality in general. We could have avoided this by looking trough the materials in a more meticulous manner.
