### ISSUE TITLE
Project Discussion (Meeting Pt 1) 12 OCT 2022

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#61]
Project meeting to discuss about the below listed items

1) Github project board standardization (discuss about how to allocate issues and close issues in a proper manner) 
2) Allocate who to do sequence diagrams and deadline for it. 
3) Allocate who to do class diagram and the deadline for it. 
4) Allocate who to do component diagram and the deadline for it (should be started after class diagram) 
5) Reflection on previous M1 report, discuss what went well and what didn't. List down points on how to improve (by 16 OCT 2022)

**Comment by ShadeRemix** [comment]
Meeting Minutes

1.  Whenever an issue is opened up proper title and tagged with category eg. (Diagram) for diagrams and deadlines must be specified.
2. Sequence diagram will be handled by Jun hao, Edwin and Zi Ping by 16 Oct 2022.
3. Class diagram will be done by Yu Xiang by 16 Oct 2022.
4. Component diagram will be done by all after class diagram is completed.
5. The reflections has been filed and completed by all members
