### ISSUE TITLE
Creation of Sequence Diagrams (Diagram) 16th Oct 2022

### ISSUE THREAD

**Issue by edwin3746** [LawJunHao/ICT2201-Team-Project-T8#62]
As part of M2 3.2 Detailed Design section, sequence diagrams based on our use case descriptions will be created and used to explain design flow between objects. Explanation is also needed with the sequence diagrams.

Deadline: To be done by 16th October 2022

**Comment by LawJunHao** [comment]
Notable Use Case numbers (Refer to M1 Report) 
1 - Login (Admin/Manager/Staff) - 
3 - Add account (Admin) - 
6 - View workload (Manager) -
7 - Allocate Job (Manager) -
10 - View assignment and workload (Staff) - Law Jun Hao
12 - Add Availability (Staff) -
14 - Reject Work Allocated (Staff) -

**Comment by LawJunHao** [comment]
Once done please leave a comment as well as date of completion and a SS of the sequence disgram in this thread, thank you

**Comment by ShadeRemix** [comment]
Item 1, Sequence Diagram for Login Done.



![Image](https://user-images.githubusercontent.com/94280261/195856442-997c676c-3223-48ea-b3ec-d00babc20dba.png)

**Comment by edwin3746** [comment]
Sequence diagram completed for Add account (Admin) use case on Oct 15

![Image](https://user-images.githubusercontent.com/64019173/195990641-19c5b94b-9193-41d6-8d47-de2586b94881.png)

**Comment by LawJunHao** [comment]
Sequence diagram for View Workload for manager done on 15 Oct

![Image](https://user-images.githubusercontent.com/92876312/195992020-f6de75f6-4efa-46c6-b5a8-d6f5aa3cfa0e.PNG)

**Comment by LawJunHao** [comment]
I've seen everyone has submitted their draft for the work done, we shall hold a mini meeting soon to discuss whether the diagrams we came up with are correct or wrong. The meeting shall be held on 16 oct 2022 9pm.
