### ISSUE TITLE
Creation of Component Diagram (Diagram) 20th Oct 2022

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#63]
This should be done after the completion of class diagram on Yu Xiang side. If Yu Xiang hasn't finish his work by 16th Oct anyone who is free can comment here to state that they are going to help him speed up his work.

**Comment by Excelic** [comment]
Componenet diagram would have to be delayed until we have finalised final entity diagram

**Comment by LawJunHao** [comment]
New dateline is 24th OCT (As discussed on 21st Oct 2nd Meeting for M2)

**Comment by Excelic** [comment]
![Image](https://user-images.githubusercontent.com/24997390/197320124-62229825-f898-4d9f-b0f0-552d570c9881.png)

Leaving this as the base for our component diagram on the time being

**Comment by edwin3746** [comment]
Synced up component diagram with class diagram on 22nd Oct as per one of the agenda of 3rd meeting

![Image](https://user-images.githubusercontent.com/64019173/197340981-d6a0ef95-e271-44da-9d6a-a9d00db97424.png)

**Comment by LawJunHao** [comment]
Acknowledge and checked with group memebers. This case can be closed as of 22nd Oct 2022.
