### ISSUE TITLE
Creation of Class Diagram (Diagram) 16th Oct 2022

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#64]
To be completed by 16th Oct 2022 by Yu Xiang. 
If Yu xiang is struggling to meet with deadline anyone who is free and completed sequence diagram can come over and help him (please leave a comment if you do help him)

**Comment by Excelic** [comment]
![Image](https://user-images.githubusercontent.com/24997390/195773941-47160778-f438-410c-9b53-24ff59934a74.png)

update on class diagram

**Comment by Excelic** [comment]
![Image](https://user-images.githubusercontent.com/24997390/195992266-f4838356-0590-49f5-9e31-ae26081403d9.jpg)

update on class diagram based on the latest iteration of initial class diagram

**Comment by Excelic** [comment]
![Image](https://user-images.githubusercontent.com/24997390/197141895-15224d76-07b0-4a7e-8ea2-1be800782ee4.jpg)

Revamp of diagramm. we will need to confirm if our diagram between squence and entity are sync, follow that we would need to decide whether the addition of boundary is correct and the need of adding interface classes

**Comment by Excelic** [comment]
![Image](https://user-images.githubusercontent.com/24997390/197243010-9d1f7e95-6618-4036-8cd8-5779253c0bf4.png)

In sync with sequence diagram, changes will be if deemed necessary
