### ISSUE TITLE
Split up tasks for M2 (M2 Report) 28 OCT 2022

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#72]
As per team discussion, we are lacking in 4.1 Use case model diagram(updated), 5.1.1 component diagram (need to be double confirmed), 5.1.3 Entity class modelling, everyone write one paragraph each for 5.1.2, 6.0 project plan needs more detailed description. 9.0 missing class diagram.

- [x] 2.1 Update the use case model diagram and upload inside report  -> Yu Xiang
- [x] 2.2 UI Requirements -> ALL 
- [x] 5.1.1 Confirm component diagram with prof and upload inside report -> Yu Xiang
- [x] 5.1.2 All Sequence Diagrams each need min a paragraph of description. 
- [x] Sequence Diagram Description 1 -> Zi Ping
- [x] Sequence Diagram Description 2 -> Edwin
- [x] Sequence Diagram Description 3 -> Jun Hao
- [x] Sequence Diagram Description 4 -> Zi Ping
- [x] Sequence Diagram Description 5 -> Jun Hao
- [x] Sequence Diagram Description 6 -> Edwin
- [x] Sequence Diagram Description 7 -> Jun Hao
- [x] 5.1.3 Entity class modelling (aka class diagram) upload once component diagram is confirmed in the previous point -> Everyone
- [x] 6.0 Description and explanation for project plan schedule -> Jun Hao
- [x] 9.0 Upload missing class diagram -> Yu Xiang

**Comment by LawJunHao** [comment]
Sequence diagrams done and uploaded to the document as of 28/10/2022. Checked by me and approved.

**Comment by ShadeRemix** [comment]
Seqeunce diagrams are uploaded

![Image](https://user-images.githubusercontent.com/94280261/198359003-419d8fcf-5a77-4d52-861c-160a159d8c5f.png)

**Comment by LawJunHao** [comment]
2.2 Completed and checked at 28 OCT 2022

![Image](https://user-images.githubusercontent.com/92876312/198624854-1597adec-1871-4903-b7a5-97c0d8b2a4fa.png)

**Comment by LawJunHao** [comment]
6.0 Done and checked at 28 OCT 2022

![Image](https://user-images.githubusercontent.com/92876312/198626047-d20da209-31ff-4f98-a734-30bbf66af807.png)

**Comment by edwin3746** [comment]
Update task 4.1 on behalf of Yu Xiang. He has added the updated component diagram in the report on 28th Oct





![Image](https://user-images.githubusercontent.com/64019173/198627181-27f95ed2-6a68-403c-88b0-8e39d412d518.png)

**Comment by LawJunHao** [comment]
Tasks done and completed as of 28 Oct 2022, closed by Jun Hao
