### ISSUE TITLE
Creation of Black and white box test for "Login" function  (M3 Report) 23rd NOV 2022

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#73]
Creation of black and white box to be done by 3rd Nov 2022. 
Whitebox replit link: https://replit.com/join/wglbpnemxa-shaderemix 
Whitebox draw.io link: https://drive.google.com/file/d/1WUVFtjK64DaFqjg1ydW8zyuT211GHmTE/view?usp=sharing

Blackbox allocation for the team, to be complete with explanation and test case:

- [x] 1) Login Function --> Edwin 
- [x] 2) View User Account --> Edwin 
- [x] 3) Add Account --> Edwin 
- [x] 4) Edit User Account --> Yu Xiang 
- [x] 5) Send email --> Yu Xiang 
- [x] 6) View Workload (Manager) --> Yu Xiang
- [x] 7) Allocate Job (Manager) --> Jun Hao 
- [x] 8) View Availability (Manager) --> Jun Hao 
- [x] 9) Rejection Approval (Manager) --> Jun Hao
- [x] 10) View Assignment and workload (Staff) --> Jun Hao
- [x] 11) Indicate Job Preference (Staff) --> Zi Ping
- [x] 12) Add Availability (Staff) --> Zi Ping
- [x] 13) Edit Availability (Staff) --> Zi Ping
- [x] 14) Reject Job Assigned (Staff) --> Zi Ping

Once done screenshot and comment it under

**Comment by LawJunHao** [comment]
Job Allocation (Manager) Blackbox 

![Image](https://user-images.githubusercontent.com/92876312/203425035-d7339666-4f72-4dd0-90c5-839b85edf70b.png)

**Comment by edwin3746** [comment]
![Image](https://user-images.githubusercontent.com/64019173/203570659-a111baa0-4069-4ee1-86a1-374b6173e792.png)



![Image](https://user-images.githubusercontent.com/64019173/203570701-e5ab8975-a17c-456c-a41e-978969b998ef.png)



![Image](https://user-images.githubusercontent.com/64019173/203570750-2c0ada02-a543-430f-980f-809a68644dbe.png)



![Image](https://user-images.githubusercontent.com/64019173/203570774-236482f5-28a7-4ab6-a21c-3d2b8f01dd35.png)

**Comment by ShadeRemix** [comment]
11) indicate job preference done

![Image](https://user-images.githubusercontent.com/94280261/203595612-5976d681-063a-46fa-9927-82eb3c993353.png)

12) add availbility done

![Image](https://user-images.githubusercontent.com/94280261/203595723-4686544d-5dfb-49a3-aea0-b4af636bd64a.png)

13) edit availbility done

![Image](https://user-images.githubusercontent.com/94280261/203595812-40fbdf09-dabb-4d3d-b261-f71b93aea41f.png)

![Image](https://user-images.githubusercontent.com/94280261/203595867-90fe50ac-ecaa-4f68-907a-c6409440b8a7.png)

14) reject job assigned done

![Image](https://user-images.githubusercontent.com/94280261/203595955-6f7e76f1-e6d4-4f12-99fa-4bb0e8a3e4f4.png)

**Comment by Excelic** [comment]
Edit User Account - done

![Image](https://user-images.githubusercontent.com/24997390/203677583-ac68cb44-1b5f-421b-b256-8477566db03f.png)

Send email - done

![Image](https://user-images.githubusercontent.com/24997390/203677660-7e96fca7-11b5-4e95-aa84-7e3173018394.png)

View Workload - done

![Image](https://user-images.githubusercontent.com/24997390/203677755-c6a1b5e5-c163-4ae8-991c-908e45c9b6e1.png)

**Comment by LawJunHao** [comment]
Control Flow Diagram for whitebox

![Image](https://user-images.githubusercontent.com/92876312/203922346-0d69e4fd-e890-4146-bb13-3005f2c2af4b.png)

Psuedo code for whitebox

![Image](https://user-images.githubusercontent.com/92876312/203922470-4b31a682-89cc-424f-8049-734e38716e1a.png)

**Comment by LawJunHao** [comment]
I have checked all the diagrams uploaded and have vetted with the team. Good job, case can be closed.
