### ISSUE TITLE
M2 Feedback Action Items

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#75]
Need correlation in class diagram and component diagram
-we have more interfaces in component than class diagram

Sequence diagram
-Use object name: class name notation
-Need specify if we use sql or not and need to put in query statements

**Comment by Excelic** [comment]
Feedback given:

1. project board not following gantt chart
2. retropection for M1 did not have a summary

Action to be taken:

1. Project Board to be aligned with the right numbering (in the title) that was stated in the gantt chart
2. M2 onward to have a summary

**Comment by ShadeRemix** [comment]
For M3 we need to fix these issues.

- [ ] Align the number of interfaces between component diagram and class diagram (Yu Xiang)
- [ ] Use object name: Class name notation for our sequence diagrams. (JunHao, ziping)
- [ ] Decide and put in the report if the team is using mysql or other RBMS databases and update class and sequence functions

**Comment by edwin3746** [comment]
Add account and Login Sequence diagrams updated with SQL statements

![Image](https://user-images.githubusercontent.com/64019173/203702796-f0b2ab3d-c1ba-4407-a660-1f10722e5d88.png)



![Image](https://user-images.githubusercontent.com/64019173/203702810-1759ea70-1d31-49d1-bfc8-0c2a14b3e441.png)

**Comment by ShadeRemix** [comment]
Name updated


![Image](https://user-images.githubusercontent.com/94280261/204077130-7ad40724-06f1-4649-9a8c-e2be214a631a.png)



![Image](https://user-images.githubusercontent.com/94280261/204077133-03bb4d3b-3ac9-4523-be46-771512fe9735.png)

**Comment by LawJunHao** [comment]
![Image](https://user-images.githubusercontent.com/92876312/204089425-67b7df2a-03d2-4abd-a7fd-bcbb8f119d3e.PNG)
![Image](https://user-images.githubusercontent.com/92876312/204089427-9d0d5eaf-3481-4497-bfa0-af48e5d7dd75.PNG)
![Image](https://user-images.githubusercontent.com/92876312/204089426-45b920c7-35f0-4fb4-ba9b-187080ade61a.PNG)

**Comment by LawJunHao** [comment]
All sequence diagrams are updated accoridngly and vetted with the team. Good job, case can be closed.
