### ISSUE TITLE
What went well in milestone 2

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#76]
Provide points that went well for M2.

**Comment by ShadeRemix** [comment]
Team coordinated well when designing the diagrams, everyone was on track and ensured that functions are consistent to the best of our ability

**Comment by edwin3746** [comment]
Project board saw an improvement in updates. There were more precise updates regularly, and better allocation of tasks. With a new standardisation of naming convention for issues, the project board is organised better as well.

**Comment by LawJunHao** [comment]
Now we initiated adding images in the comments of the issues to prove work done as well as the progress of it. This not only improves the offline communitcation between affected team members but also serves as a form of archive for previous iterations of models that were done.

**Comment by LawJunHao** [comment]
Good points given, I will now close the case as of 10/11/2022
