### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ShadeRemix** [LawJunHao/ICT2201-Team-Project-T8#78]

**Comment by edwin3746** [comment]
Summary:

1. Project board issue numbering and numbering with gantt chart:

 Jun hao volunteered to help out with the alignment of gantt chart tasks with the Github issues.

2. Collation and summarisation of issues:
The rest of the team members will focus on collating and summarising all pointers stated from other team members.

**Comment by LawJunHao** [comment]
Good points given, I will now close the case as of 10/11/2022
