### ISSUE TITLE
Creation of state diagram (M3 Report) 24th NOV 2022

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#81]
State Diagram Creation base off previously allocated blackbox creation list. 

Ensure that State Diagram covers all of the test cases derived from Black Box Testing

- [x] 1) Login Function --> Edwin 
- [x] 2) View User Account --> Edwin 
- [x] 3) Add Account --> Edwin 
- [x] 4) Edit User Account --> Yu Xiang 
- [x] 5) Send email --> Yu Xiang 
- [x] 6) View Workload (Manager) --> Yu Xiang
- [x] 7) Allocate Job (Manager) --> Jun Hao 
- [x] 8) View Availability (Manager) --> Jun Hao 
- [x] 9) Rejection Approval (Manager) --> Jun Hao
- [x] 10) View Assignment and workload (Staff) --> Jun Hao
- [x] 11) Indicate Job Preference (Staff) --> Zi Ping
- [x] 12) Add Availability (Staff) --> Zi Ping
- [x] 13) Edit Availability (Staff) --> Zi Ping
- [x] 14) Reject Job Assigned (Staff) --> Zi Ping

Once done screenshot and comment it under

**Comment by ShadeRemix** [comment]
11) Indicate job preference done



![Image](https://user-images.githubusercontent.com/94280261/203569448-c532dacd-3538-4f27-9adb-7f063cd50344.png)

**Comment by ShadeRemix** [comment]
![Image](https://user-images.githubusercontent.com/94280261/204004736-c853e22e-9ba9-4d4e-8c67-afcbea0c23c9.png)

**Comment by LawJunHao** [comment]
Checked and vetted with the team. Good job, case can be closed.
