### ISSUE TITLE
M3 Submission Materials to Prepare for (M3 Report) 26th NOV 2022

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#82]
Link to the google docs: https://docs.google.com/document/d/18d22J4DqBGHM-MkREKNA_8zCkvYunkbtpay5upvL3Co/edit?usp=sharing

Parts to write for the report

- [x] 1) Blackbox  --> ALL to chip in and help
- [x] 2) Whitebox  --> ALL to chip in and help
- [x] 3) State Diagram  --> ALL to chip in and help
- [x] 4) SS of Prototype  --> Edwin
- [x] 5) M2 Feedback/Improvement   --> ALL to chip in and help
- [x] 6) Gantt Chart --> Yu Xiang, Zi Ping 
- [x] 7) Reflection ---> All

Video

- [x] 3:30s video explaination of the prototype w narration --> Jun Hao

**Comment by ShadeRemix** [comment]
Gantt Chart updated


![Image](https://user-images.githubusercontent.com/94280261/203318129-42de8ae4-c38e-4a4f-ba7a-23cfde00d0e2.png)

**Comment by LawJunHao** [comment]
Whitebox materials for google docs are here 

![Image](https://user-images.githubusercontent.com/92876312/203929434-8cdc5cbb-b2f1-4648-812f-51e179179e83.PNG)
![Image](https://user-images.githubusercontent.com/92876312/203929433-85419954-3140-4129-889c-b666e4e5c1fe.PNG)
![Image](https://user-images.githubusercontent.com/92876312/203929432-39a5abb6-8728-43b4-b591-c38530493064.PNG)
![Image](https://user-images.githubusercontent.com/92876312/203929431-ced18954-25ed-4b4f-8252-8210fd65a2ae.PNG)

**Comment by LawJunHao** [comment]
Checked all materials for M3 and vetted with the team. Good job, case can be closed.
