### ISSUE TITLE
Consultation with client (M3 Meeting)  24th NOV 2022

### ISSUE THREAD

**Issue by LawJunHao** [LawJunHao/ICT2201-Team-Project-T8#83]

**Comment by edwin3746** [comment]
Q: Check pseudocode whether is correct (Use multiple functions or just one function)
A: Node only comes from main logic, not from helper function (not counted for the 15 nodes)

Q: Are nested loops ok
A. It is fine, represent them (based on the loop type) accordingly

Q: What to include in state diagram, (based on use case or black box tables/test case)
A. System state diagram (only 1) has to be informed by the use cases. Most if not all use cases must be represented within the System State Diagram

Q. Boundary analysis and equivalence partition required or just decision tables 
A. Must be done together with decision tables, not a separate section on itself 

Q. Range of inputs 
A. Recognize boundaries, equivalence partition has 3 partitions

Q. How many test cases required for each BB decision table
A. 
1 particular use case, generate all different cases that could go wrong
1 use case = generate few test cases
